.PHONY: install dev build typecheck lint test test-coverage

install:
	npm install

dev:
	npm run dev

build:
	npm run build

typecheck:
	npm run typecheck

lint:
	npx web-ext lint --source-dir dist

test:
	npm test


test-coverage:
	npm run test:coverage

